from enum import StrEnum


class ContractStatus(StrEnum):
    DRAFT = "DRAFT"
    ANALYZING = "ANALYZING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NEGOTIATING = "NEGOTIATING"
    READY_TO_SIGN = "READY_TO_SIGN"
    SIGNING = "SIGNING"
    SIGNED = "SIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    RENEWAL_DUE = "RENEWAL_DUE"


class AdjustmentRequestStatus(StrEnum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    OPENED = "OPENED"
    RESPONDED = "RESPONDED"
    CONFIRMED = "CONFIRMED"
    EXPIRED = "EXPIRED"


class ModusignStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    ON_PROCESSING = "ON_PROCESSING"
    ON_GOING = "ON_GOING"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"
    PROCESSING_FAILED = "PROCESSING_FAILED"


class ObligationStatus(StrEnum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    DISPUTED = "DISPUTED"


class VerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    NOT_FOUND = "NOT_FOUND"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    NEEDS_CHECK = "NEEDS_CHECK"


class ReviewSignalType(StrEnum):
    MISMATCH = "MISMATCH"
    NO_BASIS = "NO_BASIS"
    UNCLEAR = "UNCLEAR"
    MISSING = "MISSING"
    NEEDS_CHECK = "NEEDS_CHECK"


class ReviewSeverity(StrEnum):
    INFO = "INFO"
    CHECK = "CHECK"
    IMPORTANT = "IMPORTANT"


class SuggestionChoice(StrEnum):
    ACCEPT = "ACCEPT"
    COMPROMISE = "COMPROMISE"
    REQUEST = "REQUEST"
