from enum import StrEnum


class ContractStatus(StrEnum):
    DRAFT = "DRAFT"
    ANALYZING = "ANALYZING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NEGOTIATING = "NEGOTIATING"
    READY_TO_SIGN = "READY_TO_SIGN"
    SIGNING = "SIGNING"
    SIGNED = "SIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    RENEWAL_DUE = "RENEWAL_DUE"


class AdjustmentRequestStatus(StrEnum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    OPENED = "OPENED"
    RESPONDED = "RESPONDED"
    CONFIRMED = "CONFIRMED"
    EXPIRED = "EXPIRED"


class ModusignStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    ON_PROCESSING = "ON_PROCESSING"
    ON_GOING = "ON_GOING"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"
    PROCESSING_FAILED = "PROCESSING_FAILED"


class InternalSignatureStatus(StrEnum):
    REQUEST_READY = "REQUEST_READY"
    REQUESTING = "REQUESTING"
    EDITING = "EDITING"
    SIGNING = "SIGNING"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"
    FAILED = "FAILED"


class ObligationStatus(StrEnum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    DISPUTED = "DISPUTED"


class AnalysisStatus(StrEnum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class StateEntityType(StrEnum):
    CONTRACT = "CONTRACT"
    ADJUSTMENT_REQUEST = "ADJUSTMENT_REQUEST"
    INTERNAL_SIGNATURE = "INTERNAL_SIGNATURE"
    OBLIGATION = "OBLIGATION"
    ANALYSIS_TASK = "ANALYSIS_TASK"


class AuditActorType(StrEnum):
    OWNER = "OWNER"
    AGENCY = "AGENCY"
    SYSTEM = "SYSTEM"


class PublicTokenScope(StrEnum):
    ADJUSTMENT_RESPONSE = "ADJUSTMENT_RESPONSE"
    OBLIGATION_EVIDENCE = "OBLIGATION_EVIDENCE"


class IdempotencyOperation(StrEnum):
    ANALYSIS_START = "ANALYSIS_START"
    ADJUSTMENT_DRAFT_CREATE = "ADJUSTMENT_DRAFT_CREATE"
    ADJUSTMENT_SEND = "ADJUSTMENT_SEND"
    AGREEMENT_CREATE = "AGREEMENT_CREATE"
    SIGNATURE_REQUEST = "SIGNATURE_REQUEST"
    EVIDENCE_LINK_CREATE = "EVIDENCE_LINK_CREATE"


class AuditEventType(StrEnum):
    CONTRACT_CREATED = "CONTRACT_CREATED"
    CONTRACT_STARTED = "CONTRACT_STARTED"
    CONTRACT_COMPLETED = "CONTRACT_COMPLETED"
    CONTRACT_RENEWAL_DUE = "CONTRACT_RENEWAL_DUE"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    UNDERSTOOD_TERMS_SAVED = "UNDERSTOOD_TERMS_SAVED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    ANALYSIS_RESTARTED = "ANALYSIS_RESTARTED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"
    REVIEW_ITEM_SELECTION_UPDATED = "REVIEW_ITEM_SELECTION_UPDATED"
    ADJUSTMENT_DRAFT_CREATED = "ADJUSTMENT_DRAFT_CREATED"
    ADJUSTMENT_SENT = "ADJUSTMENT_SENT"
    ADJUSTMENT_OPENED = "ADJUSTMENT_OPENED"
    ADJUSTMENT_RESPONDED = "ADJUSTMENT_RESPONDED"
    ADJUSTMENT_CONFIRMED = "ADJUSTMENT_CONFIRMED"
    ADJUSTMENT_EXPIRED = "ADJUSTMENT_EXPIRED"
    AGREEMENT_CREATED = "AGREEMENT_CREATED"
    SIGNATURE_DRAFT_CREATED = "SIGNATURE_DRAFT_CREATED"
    SIGNATURE_REQUESTED = "SIGNATURE_REQUESTED"
    SIGNATURE_STARTED = "SIGNATURE_STARTED"
    SIGNATURE_COMPLETED = "SIGNATURE_COMPLETED"
    SIGNATURE_ABORTED = "SIGNATURE_ABORTED"
    SIGNATURE_FAILED = "SIGNATURE_FAILED"
    OBLIGATION_CREATED = "OBLIGATION_CREATED"
    EVIDENCE_LINK_CREATED = "EVIDENCE_LINK_CREATED"
    EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED"
    EVIDENCE_APPROVED = "EVIDENCE_APPROVED"
    EVIDENCE_DISPUTED = "EVIDENCE_DISPUTED"
    RENEWAL_DECISION_SAVED = "RENEWAL_DECISION_SAVED"


class VerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    NOT_FOUND = "NOT_FOUND"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    NEEDS_CHECK = "NEEDS_CHECK"


class ReviewSignalType(StrEnum):
    MISMATCH = "MISMATCH"
    NO_BASIS = "NO_BASIS"
    UNCLEAR = "UNCLEAR"
    MISSING = "MISSING"
    NEEDS_CHECK = "NEEDS_CHECK"


class ReviewSeverity(StrEnum):
    INFO = "INFO"
    CHECK = "CHECK"
    IMPORTANT = "IMPORTANT"


class SuggestionChoice(StrEnum):
    ACCEPT = "ACCEPT"
    COMPROMISE = "COMPROMISE"
    REQUEST = "REQUEST"


class RenewalDecisionType(StrEnum):
    RENEW_SAME_TERMS = "RENEW_SAME_TERMS"
    RENEW_WITH_CHANGES = "RENEW_WITH_CHANGES"
    TERMINATE = "TERMINATE"


class AdjustmentResponseDecision(StrEnum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    COUNTER = "COUNTER"


class AdjustmentResolution(StrEnum):
    ACCEPT_REQUEST = "ACCEPT_REQUEST"
    ACCEPT_COUNTERPROPOSAL = "ACCEPT_COUNTERPROPOSAL"
    KEEP_ORIGINAL = "KEEP_ORIGINAL"


class AgreementClauseCategory(StrEnum):
    TERM_AND_PAYMENT = "TERM_AND_PAYMENT"
    DELIVERABLES = "DELIVERABLES"
    TERMINATION_AND_RENEWAL = "TERMINATION_AND_RENEWAL"
    RIGHTS_AND_SAFETY = "RIGHTS_AND_SAFETY"
    OTHER = "OTHER"


class AgreementClauseOutcome(StrEnum):
    AGREED = "AGREED"
    KEPT_ORIGINAL = "KEPT_ORIGINAL"


class AgreementClauseDisposition(StrEnum):
    AGREED = "AGREED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"


class ExtractedField(StrEnum):
    CONTRACT_PARTY_OWNER = "contract_party_owner"
    CONTRACT_PARTY_AGENCY = "contract_party_agency"
    CONTRACT_SIGNED_DATE = "contract_signed_date"
    CONTRACT_START_DATE = "contract_start_date"
    CONTRACT_END_DATE = "contract_end_date"
    MONTHLY_AMOUNT = "monthly_amount"
    CONTRACT_TOTAL_AMOUNT = "contract_total_amount"
    PAYMENT_METHOD = "payment_method"
    AUTO_RENEWAL = "auto_renewal"
    CONTRACT_RENEWAL_TYPE = "contract_renewal_type"
    TERMINATION_NOTICE_DATE = "termination_notice_date"
    EARLY_TERMINATION_ALLOWED = "early_termination_allowed"
    TERMINATION_PENALTY_RATE = "termination_penalty_rate"
    REFUND_CONDITION = "refund_condition"
    ADVERTISING_CHANNEL = "advertising_channel"
    CONTENT_TYPE = "content_type"
    CONTENT_QUANTITY = "content_quantity"
    DELIVERABLE_DUE_DATE = "deliverable_due_date"
    POSTING_FREQUENCY = "posting_frequency"
    REPORTING_FREQUENCY = "reporting_frequency"
    PERFORMANCE_GUARANTEE = "performance_guarantee"
    ADVERTISING_ACCOUNT_OWNERSHIP = "advertising_account_ownership"
    CONTENT_OWNERSHIP = "content_ownership"
    SHOOTING_SAFETY = "shooting_safety"
    PORTRAIT_RIGHTS = "portrait_rights"
    PERSONAL_INFORMATION_HANDLING = "personal_information_handling"
    FACILITY_DAMAGE_LIABILITY = "facility_damage_liability"
    FALSE_ADVERTISING_LIABILITY = "false_advertising_liability"


class ExtractedValueType(StrEnum):
    TEXT = "TEXT"
    DATE = "DATE"
    MONEY_KRW = "MONEY_KRW"
    INTEGER = "INTEGER"
    PERCENT = "PERCENT"
    BOOLEAN = "BOOLEAN"


class DetectionMethod(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"
    MODEL = "MODEL"
    HYBRID = "HYBRID"


class ExtractedSourceType(StrEnum):
    CONTRACT_DOCUMENT = "CONTRACT_DOCUMENT"
    DOCUMENTED_EXPLANATION = "DOCUMENTED_EXPLANATION"


class ReviewBasisType(StrEnum):
    OFFICIAL_SOURCE = "OFFICIAL_SOURCE"
    INTERNAL_RULE = "INTERNAL_RULE"


class ReviewItemStatus(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    SELECTED = "SELECTED"
    SENT = "SENT"
    RESOLVED = "RESOLVED"
    KEPT_ORIGINAL = "KEPT_ORIGINAL"
