from enum import StrEnum


class ErrorCode(StrEnum):
    DOCUMENT_PARSE_FAILED = "DOCUMENT_PARSE_FAILED"
    ANALYSIS_SCHEMA_INVALID = "ANALYSIS_SCHEMA_INVALID"
    ANALYSIS_START_FAILED = "ANALYSIS_START_FAILED"
    ADJUSTMENT_LINK_EXPIRED = "ADJUSTMENT_LINK_EXPIRED"
    OBLIGATION_LINK_EXPIRED = "OBLIGATION_LINK_EXPIRED"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    MODUSIGN_REQUEST_FAILED = "MODUSIGN_REQUEST_FAILED"
    WEBHOOK_DUPLICATED = "WEBHOOK_DUPLICATED"
    WEBHOOK_AUTH_FAILED = "WEBHOOK_AUTH_FAILED"
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    ADJUSTMENT_TOKEN_SCOPE_INVALID = "ADJUSTMENT_TOKEN_SCOPE_INVALID"
    OBLIGATION_TOKEN_SCOPE_INVALID = "OBLIGATION_TOKEN_SCOPE_INVALID"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
