from enum import StrEnum


class ErrorCode(StrEnum):
    DOCUMENT_PARSE_FAILED = "DOCUMENT_PARSE_FAILED"
    ANALYSIS_SCHEMA_INVALID = "ANALYSIS_SCHEMA_INVALID"
    ADJUSTMENT_LINK_EXPIRED = "ADJUSTMENT_LINK_EXPIRED"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    MODUSIGN_REQUEST_FAILED = "MODUSIGN_REQUEST_FAILED"
    WEBHOOK_DUPLICATED = "WEBHOOK_DUPLICATED"
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
